name: Pydrofoil-from-sail

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: download build script
      run: |
        echo github ref ${GITHUB_REF} ${GITHUB_REF_NAME}
        wget https://raw.githubusercontent.com/pydrofoil/pydrofoil/${GITHUB_REF_NAME}/build-pydrofoil-from-sail.sh
    - name: Add opam2 PPA
      run: sudo add-apt-repository -y ppa:avsm/ppa
    - name: Install packages
      run: sudo apt install -y opam zlib1g-dev pkg-config libgmp-dev z3 device-tree-compiler
    - name: Init opam
      run: opam init --disable-sandboxing -y
    - name: Install sail
      run: opam install -y sail=0.14
    - uses: actions/checkout@master
      with:
        repository: riscv/sail-riscv

    - name: ls
      run: |
        ls -la

    - name: run build script
      run: |
        eval $(opam env) && bash build-pydrofoil-from-sail.sh ${GITHUB_REF_NAME}

    - name: version
      run: |
        ./pydrofoil-riscv --version

    - name: run two tests
      run: |
        ./pydrofoil-riscv --rv32 test/riscv-tests/rv32ui-p-addi.elf
        ./pydrofoil-riscv test/riscv-tests/rv64ui-p-addi.elf
