# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pydrofoil

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: uname
      run: |
        uname -s
        uname -a

    - name: Set up PyPy 2.7
      uses: actions/setup-python@v4
      with:
        python-version: "pypy-2.7-v7.3.9"

    - name: install dependencies and create virtualenv
      run: |
        make pypy_binary/bin/python
        make pypy/rpython/bin/rpython

    - name: Test with pytest
      run: |
        make pydrofoil-test

    - name: Translate and run binary
      run: |
        make pydrofoil-riscv

    - name: Run two RISC-V tests
      run: |
        ./pydrofoil-riscv riscv/input/rv64ui-p-addi.elf
        ./pydrofoil-riscv --rv32 riscv/input/rv32ui-p-addi.elf

    - name: Boot Linux
      run: |
        ./pydrofoil-riscv -b riscv/input/rv64-64mb.dtb riscv/input/rv64-linux-4.15.0-gcc-7.2.0-64mb.bbl -l 230000000

    - uses: actions/upload-artifact@v3
      with:
        name: pydrofoil-riscv
        path: ./pydrofoil-riscv
