name: Pydrofoil WSL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3

    - name: Setup WSL
      uses: Vampire/setup-wsl@v1
      with:
        distribution: Ubuntu-20.04
        additional-packages:
          build-essential


    - name: ls
      shell: wsl-bash {0}
      run: ls -la

    - name: extra packages
      shell: wsl-bash {0}
      run: sudo apt install build-essential

    - name: Translate, run, test binary
      shell: wsl-bash {0}
      run: |
        make pydrofoil-riscv
        ./pydrofoil-riscv --version
        ./pydrofoil-riscv riscv/input/rv64ui-p-addi.elf
        ./pydrofoil-riscv --rv32 riscv/input/rv32ui-p-addi.elf

